export enum ModuleType {
  QUALIDADE = "QUALIDADE",
  SEGURANCA_TRABALHO = "SEGURANCA_TRABALHO",
  OBRAS_INVESTIMENTO = "OBRAS_INVESTIMENTO",
  OBRAS_GLOBAL = "OBRAS_GLOBAL",
  CANTEIRO = "CANTEIRO",
}

export enum UserRole {
  ADMIN = "ADMIN",
  GESTOR = "GESTOR",
  FISCAL = "FISCAL",
}

export enum ChecklistAnswer {
  CONFORME = "CONFORME",
  NAO_CONFORME = "NAO_CONFORME",
  NAO_APLICAVEL = "NAO_APLICAVEL",
}

export enum InspectionStatus {
  RASCUNHO = "RASCUNHO",
  FINALIZADA = "FINALIZADA",
  PENDENTE_AJUSTE = "PENDENTE_AJUSTE",
  RESOLVIDA = "RESOLVIDA",
}

export enum SyncState {
  PENDING_SYNC = "PENDING_SYNC",
  SYNCING = "SYNCING",
  SYNCED = "SYNCED",
  SYNC_ERROR = "SYNC_ERROR",
}
