export enum ModuleType {
  CAMPO = "CAMPO",
  SEGURANCA_TRABALHO = "SEGURANCA_TRABALHO",
  REMOTO = "REMOTO",
  POS_OBRA = "POS_OBRA",
}


export enum UserRole {
  ADMIN = "ADMIN",
  GESTOR = "GESTOR",
  FISCAL = "FISCAL",
}

export enum ChecklistAnswer {
  CONFORME = "CONFORME",
  NAO_CONFORME = "NAO_CONFORME",
  NAO_APLICAVEL = "NAO_APLICAVEL",
}

export enum InspectionStatus {
  RASCUNHO = "RASCUNHO",
  FINALIZADA = "FINALIZADA",
  PENDENTE_AJUSTE = "PENDENTE_AJUSTE",
  RESOLVIDA = "RESOLVIDA",
}
