export enum ModuleType {
  OBRAS_INVESTIMENTO = "OBRAS_INVESTIMENTO",
  CAMPO = "CAMPO",
  REMOTO = "REMOTO",
  POS_OBRA = "POS_OBRA",
  SEGURANCA_TRABALHO = "SEGURANCA_TRABALHO",
}


export enum UserRole {
  ADMIN = "ADMIN",
  GESTOR = "GESTOR",
  FISCAL = "FISCAL",
}

export enum ChecklistAnswer {
  CONFORME = "CONFORME",
  NAO_CONFORME = "NAO_CONFORME",
  NAO_APLICAVEL = "NAO_APLICAVEL",
}

export enum InspectionStatus {
  RASCUNHO = "RASCUNHO",
  FINALIZADA = "FINALIZADA",
  PENDENTE_AJUSTE = "PENDENTE_AJUSTE",
  RESOLVIDA = "RESOLVIDA",
}

export enum InspectionScope {
  TEAM = "TEAM",
  COLLABORATOR = "COLLABORATOR",
}

export enum InvestmentWorkStatus {
  EM_ANDAMENTO = "EM_ANDAMENTO",
  PARALISADA = "PARALISADA",
  FINALIZADA = "FINALIZADA",
  CANCELADA = "CANCELADA",
}
